---
- hosts: localhost
  tasks:
  - name: download k3d
    ansible.builtin.command: curl https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh -o /tmp/installk3d.sh
    args:
      creates: /tmp/installk3d.sh
  - name: install k3d
    ansible.builtin.command: bash /tmp/installk3d.sh
    args:
      creates: /usr/local/bin/k3d
  - name: download helm
    ansible.builtin.command: curl -o /tmp/installhelm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    args:
      creates: /tmp/installhelm.sh
  - name: install helm
    ansible.builtin.command: bash /tmp/installhelm.sh
    args:
      creates: /usr/local/bin/helm
  - name: change permissions on helm
    become: true
    ansible.builtin.file:
      path: /usr/local/bin/helm
      mode: o=x  
  - name: download kubectl
    ansible.builtin.command: curl -Lo /tmp/installkubectl https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
    args:
      creates: /tmp/installkubectl
  - name: install kubectl
    ansible.builtin.command: sudo install -o root -g root -m 0755 /tmp/installkubectl /usr/local/bin/kubectl
    args:
      creates: /usr/local/bin/kubectl

  - name: create cluster
    ansible.builtin.command: k3d cluster create local-k8s
    args:
      creates: ~/.kube/config
  - name: Deploy Wordpress chart from bitnami
    kubernetes.core.helm:
      name: wordpress
      chart_ref: oci://registry-1.docker.io/bitnamicharts/wordpress
      release_namespace: default

  - name: Add Prometheus Helm repo
    ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  - name: Add Grafana Helm repo
    ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
  - name: Update Helm repos
    ansible.builtin.command: helm repo update

  - name: Create monitoring namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: monitoring

  - name: Install Prometheus
    kubernetes.core.helm:
      name: prometheus
      chart_ref: prometheus-community/prometheus
      release_namespace: monitoring

  - name: Install Grafana
    kubernetes.core.helm:
      name: grafana
      chart_ref: bitnami/grafana
      release_namespace: monitoring



